##########
# SUPPLY #
##########

[elec_supply]
locations = ["bld1"]
capacities.bld1 = ['inf']
costs_invest_per_use.bld1 = [10.2, 0.2, 20.2, 10.0]# [0.14, 0.08, 0.22, 0.02] # 0.139
co2_per_use.bld1 = [11.0, 1.0, 21.0, 10.0]  #0 #0.0126
nodes.rep.energy_carrier = 'elec'
nodes.rep.node_type = 'supply'

[gas_supply]
locations = ["bld1"]
capacities.bld1 = ['inf']
# costs_invest_per_use.all = 2.0
costs_invest_per_use.bld1 = [1.1, 0.1, 2.1, 1.0] #[0.15, 0.05, 0.25, 0.10] #0.119 #[0.12, 0.06, 0.20, 0.02] 
co2_per_use.bld1 = [10, 10, 30, 10] #0.228
nodes.rep.energy_carrier = 'gas'
nodes.rep.node_type = 'supply'

[solar_supply]
locations = ["bld1"]
capacities.bld1 = ['inf']
costs_invest_per_use.all = 0.0001
nodes.rep.energy_carrier = 'solar'
nodes.rep.node_type = 'solar'
capacity_max_temp.bld1 = ['bld1.csv', 'solar']

##########
# DEMAND #
##########

[elec_demand]
locations = ['bld1']
nodes.rep.energy_carrier = 'elec'
nodes.rep.node_type = 'demand'
capacity_min_temp.bld1 = ['bld1.csv', 'elec']

[heat_demand]
locations = ['bld1']
nodes.rep.energy_carrier = 'heat'
nodes.rep.node_type = 'demand'
capacity_min_temp.bld1 = ['bld1.csv', 'heat']

##############
# CONVERTERS #
##############

[chp_gas]
locations = ['bld1']
costs_invest_per_cap.bld1 = 100 #347.7 # applies to representative node
costs_OM_per_cap.bld1 = 10 #4.34 # applies to representative node
# capacities.bld1 = [2240]
capacity_max.bld1 = 320 #1240 # applies to representative node
capacity_min.bld1 = 120 #40
capacity_stepsize.bld1 = 100
nodes.rep.energy_carrier = 'elec'
nodes.rep.node_type = 'output'
nodes.gas_in.energy_carrier = 'gas'
nodes.gas_in.node_type = 'input'
nodes.heat_out.energy_carrier = 'heat'
nodes.heat_out.node_type = 'output'
weights.gas_in.rep.0 = 0.14
weights.gas_in.heat_out.0 = 0.26


[boiler_gas]
locations = ['bld1']
costs_invest_per_cap.bld1 = 50 #315  # applies to representative node
costs_OM_per_cap.bld1 = 5 #3.51 # applies to representative node
# capacities.bld1 = [4050]
capacity_max.bld1 = 320 #1050
capacity_min.bld1 = 120 #50
capacity_stepsize.bld1 = 100
nodes.rep.energy_carrier = 'heat'
nodes.rep.node_type = 'output'
nodes.gas_in.energy_carrier = 'gas'
nodes.gas_in.node_type = 'input'
weights.gas_in.rep.0 = 0.9

[pv]
locations = ['bld1']
capacity_max.bld1 = 15 #55
capacity_min.bld1 = 5
capacity_stepsize.bld1 = 5
costs_invest_per_cap.bld1 = 280 # per m2 not kw peak
# costs_OM_per_cap.bld1 = 1 # per m2 not kw peak
nodes.rep.energy_carrier = 'solar'
nodes.rep.node_type = 'area'
nodes.elec_out.energy_carrier = 'elec'
nodes.elec_out.node_type = 'output'
weights.rep.elec_out.0 = 0.19


# ###########
# # STORAGE #
# ###########

[battery]
locations = ['bld1']
costs_invest_per_cap.bld1 = 1000
capacity_max.bld1 = 500
capacity_min.bld1 = 100
capacity_stepsize.bld1 = 200
# capacities.bld1 = [5000]
nodes.rep.energy_carrier = 'elec'
nodes.rep.node_type = 'store'
node.rep.capacity_min = 0.5 # minimum SOC of 5%
nodes.elec_in.energy_carrier = 'elec'
nodes.elec_in.node_type = 'input'
nodes_elec_in.capacity_max = 0.95 # max charge rate assumed 90%
nodes.elec_out.energy_carrier = 'elec'
nodes.elec_out.node_type = 'output'
nodes.elec_out.capacity_max = 0.95 # min charge rate assumed 90%
weights.rep.rep.0 = 0.999 # self discharge assumed 0.1%
weights.elec_in.rep.0 = 0.9 # charging efficiency assumed 100%
weights.rep.elec_out.0 = 0.9 # discharging efficiency assumed 100%